### ISSUE TITLE
PiPy version is outdated. it still shows 0.3.1

### ISSUE THREAD

**Issue by PAHXO** [linuxscout/mysam-tagmanager#6]
Hello, Please update the version on PiPy.

Some people are trying to force use the older version. [Here](https://github.com/linuxscout/mishkal/issues/50) and [here](https://github.com/linuxscout/mishkal/pull/51).

Regards

**Comment by linuxscout** [comment]
Thanks a lot @PAHXO,
I updated the version on PiPy
Regards
